// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "rulesInit": boolean;
      "ruleWarningDisabled": boolean;
      "deleteMessageDisabled": boolean;
      "menuSortBy": string;
      "showPopup": boolean;
      "rulesSortColumnIndex": number;
      "rulesSortColumnAscending": boolean;
    };
  }
}
